export const statesOfMexico = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Estado de México",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
];

export const statesCodes = {
  "Aguascalientes": "AS",
  "Baja California": "BC",
  "Baja California Sur": "BS",
  "Campeche": "CC",
  "Chiapas": "CS",
  "Chihuahua": "CH",
  "Ciudad de México": "DF",
  "Coahuila": "CL",
  "Colima": "CM",
  "Durango": "DG",
  "Guanajuato": "GT",
  "Guerrero": "GR",
  "Hidalgo": "HG",
  "Jalisco": "JC",
  "Estado de México": "MC",
  "Michoacán": "MN",
  "Morelos": "MS",
  "Nayarit": "NT",
  "Nuevo León": "NL",
  "Oaxaca": "OC",
  "Puebla": "PL",
  "Querétaro": "QT",
  "Quintana Roo": "QR",
  "San Luis Potosí": "SP",
  "Sinaloa": "SL",
  "Sonora": "SR",
  "Tabasco": "TC",
  "Tamaulipas": "TS",
  "Tlaxcala": "TL",
  "Veracruz": "VZ",
  "Yucatán": "YN",
  "Zacatecas": "ZS",
};

export const stepsDictionary = {
  "confirm-motorcycle": "Confirmar motocicleta",
  "income-source": "Ingresos / Crediticio",
  "job-description": "Empleo",
  "references-confirmation": "Referencias",
  "buro-credito-request": "Consulta BC",
  landing: "Bienvenida",
  "client-validation": "Identificación",
  "curp-generator": "Generador Curp",
  "curp-validation": "Validación Curp",
  "id-validation": "Validación INE",
  "confirm-data": "Validar información",
  "validate-applications": "Solicitudes",
  "validate-purchases": "Validar Compras",
  "error-page": "Error",
  "registration-completion-handler": "Registro completado",
  "payment-details": "Validacion INE titular de la tarjeta",
  "landing-web": "Bienvenida",
  "confirm-store": "Confirmar Sucursal",
  "web-registration": "Registrar información",
  "quote-generator": "Obtener Cotización",
  "credit-approval-result": "Evaluación de BC",
  "personal-quote": "Cotización personalizada",
  "upload-documents": "Subir documentos",
  "my-documents": "Subir documentos",
  "static-page": "Ofertas de Crédito",
  "personal-info": "Información personal",
  "update-solicitud": "Actualizar solicitud",
};

export const incomeSourceTypes = [
  "Persona Física (Asalariado)",
  "Persona Física con Actividad Empresarial",
  "Independiente Informal",
  "Persona Moral",
  "Jubilado",
  "Accionista",
];

export const incomeSourceTypesMapped = [
  { label: "Persona Física (Asalariado)", value: "PF" },
  { label: "Persona Física con Actividad Empresarial", value: "PFAE" },
  { label: "Independiente Informal", value: "Independiente Informal" },
  { label: "Persona Moral", value: "PM" },
  { label: "Jubilado", value: "Jubilado" },
  { label: "Accionista", value: "Accionista" },
];

export const incomeProofOptions = [
  "Recibo de Nómina",
  "Estados de Cuenta",
  "Declaración ante SAT",
  "No compruebo ingresos",
];

export const creditHistoryDescriptions = [
  "Siempre he pagado a tiempo",
  "Me he atrasado de 1 a 60 días",
  "Me he atrasado más de 12 meses",
  "He renegociado deudas",
  "Nunca he tenido algún crédito",
  "Me he atrasado de 61 días a 12 meses",
];

export const bankOptions = [
  "BBVA",
  "Santander",
  "Hey",
  "Banregio",
  "Maxikash",
  "Galgo",
  "Otros"
];

export const companyTypeOptions = [
  "Privada (No cotiza en bolsa de valores)",
  "Pública (Si cotiza en bolsa de valores)",
  "Empresa de Gobierno",
];

export const famRelationTypes = [
  "Padre/Madre",
  "Hermano/a",
  "Tío/a",
  "Hijo/a",
  "Abuelo/a",
  "Nieto/a",
  "Primo/a",
  "Sobrino/a",
  "Cuñado/a",
  "Suegro/a",
  "Yerno/Nuera",
  "Padrastro/Madrastra",
  "Hijastro/a",
  "Bisabuelo/a",
  "Bisnieto/a",
  "Concubino/a",
  "Otro",
];

